### ISSUE TITLE
Import not possible for DNA 3.0 databases

### ISSUE THREAD

**Issue by TimHenrichsen** [leifeld/dna#216]
Currently, DNA 3.0. databases cannot be imported into another DNA 3.0. database.

**Comment by leifeld** [comment]
There was a bug when documents with existing text and title were ignored. When that option was selected, an error was thrown in the message log (fixed in https://github.com/leifeld/dna/commit/6d36da9081a39ec1111a5024d33a2a72b0e83392). Does the problem occur with DNA 3.0 alpha 3 when the option is not selected?

**Comment by TimHenrichsen** [comment]
Yes, unfortunately, the problem still occurs. I'll send you an example database now.
